version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=password
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./data:/var/lib/clickhouse/user_files/data

  spark-master:
    image: spark:latest
    container_name: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master -h spark-master -p 7077 --webui-port 8080
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./data:/app/data

  spark-worker:
    image: spark:latest
    container_name: spark-worker
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077 -c 2 -m 2G
    depends_on:
      - spark-master
    volumes:
      - ./data:/app/data

  pipeline-runner:
    build: .
    container_name: pipeline-runner
    depends_on:
      - clickhouse
      - spark-master
    environment:
      - CLICKHOUSE_HOST=clickhouse
    volumes:
      - ./data:/app/data
      - ./kaggle.json:/app/kaggle.json
