import os
import clickhouse_connect

def load_data():
    host = os.getenv('CLICKHOUSE_HOST', 'localhost')
    client = clickhouse_connect.get_client(host=host, port=8123, username='default', password='password')

    # DDL with MergeTree. ORDER BY optimizes for categorical filtering and sorting.
    ddl = """
    CREATE TABLE IF NOT EXISTS imdb_analytics (
        tconst String,
        titleType String,
        primaryTitle String,
        originalTitle String,
        isAdult String,
        startYear Int32,
        endYear String,
        runtimeMinutes Int32,
        genres String,
        averageRating Float32,
        numVotes Int32
    ) ENGINE = MergeTree()
    ORDER BY (titleType, startYear, averageRating);
    """
    client.command(ddl)
    
    # Truncate-and-Load pattern: Empties the table without destroying the schema/metadata
    client.command("TRUNCATE TABLE imdb_analytics")

    print("Loading partitioned Parquet data into ClickHouse...")
    # ClickHouse natively reads the partitioned Parquet files generated by Spark
    insert_query = """
    INSERT INTO imdb_analytics
    SELECT * FROM file('data/lake/imdb_enriched.parquet/**/*.parquet', 'Parquet')
    """
    client.command(insert_query)
    print("Data loaded successfully!")

if __name__ == "__main__":
    load_data()
